name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-challenges:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: echo "matrix=$(ls challenges/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  docker-build-push:
    needs: list-challenges
    runs-on: ubuntu-latest

    permissions:
      packages: write

    strategy:
      matrix:
        challenge: ${{ fromJson(needs.list-challenges.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./challenges/${{ matrix.challenge }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/cerberauth/api-vulns-challenges/${{ matrix.challenge }}:latest
          cache-from: type=registry,ref=ghcr.io/cerberauth/api-vulns-challenges/${{ matrix.challenge }}:latest
          cache-to: type=inline
